[book]
authors = ["Sigurd Berg Svela"]
language = "no"
multilingual = false
src = "build/src"
title = "Sonans Tekshefte 2020"

[build]
create-missing = false

[output.latex]
latex    = true  # default = true
pdf      = true  # default = false
markdown = true  # default = false